import 'package:flutter/material.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'pricing_screen.dart';

class MenuDetailScreen extends StatelessWidget {
  final Map<String, dynamic> fullMenu;
  final String eventType;
  final String cuisine;

  const MenuDetailScreen({
    super.key,
    required this.fullMenu,
    required this.eventType,
    required this.cuisine,
  });

  // --- PDF GENERATION LOGIC ---
  Future<void> _generateAndSharePdf() async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.Page(
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Header(
                level: 0,
                child: pw.Text("$eventType Menu ($cuisine)",
                    style: pw.TextStyle(
                        fontSize: 24, fontWeight: pw.FontWeight.bold)),
              ),
              pw.SizedBox(height: 20),
              _buildPdfSection("Starters", fullMenu['starters']),
              _buildPdfSection("Main Course", fullMenu['main_course']),
              _buildPdfSection("Breads & Rice",
                  [...?fullMenu['breads'], ...?fullMenu['rice']]),
              _buildPdfSection("Desserts", fullMenu['desserts']),
              _buildPdfSection("Beverages", fullMenu['beverages']),
              pw.SizedBox(height: 20),
              pw.Text("Generated by AI Catering Planner",
                  style:
                      const pw.TextStyle(fontSize: 12, color: PdfColors.grey)),
            ],
          );
        },
      ),
    );

    // Open the standard Share/Print dialog
    await Printing.sharePdf(
        bytes: await pdf.save(), filename: 'catering_menu.pdf');
  }

  // Helper for PDF Layout
  pw.Widget _buildPdfSection(String title, List<dynamic>? items) {
    if (items == null || items.isEmpty) return pw.SizedBox.shrink();
    return pw.Container(
      margin: const pw.EdgeInsets.only(bottom: 10),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(title,
              style: pw.TextStyle(
                  fontSize: 16,
                  fontWeight: pw.FontWeight.bold,
                  color: PdfColors.blueGrey800)),
          ...items.map((item) => pw.Bullet(text: item.toString())),
          pw.SizedBox(height: 5),
        ],
      ),
    );
  }

  // --- UI BUILD ---
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("$eventType Menu"),
        backgroundColor: Colors.deepPurple,
        foregroundColor: Colors.white,
        actions: [
          // SHARE BUTTON
          IconButton(
            icon: const Icon(Icons.share),
            onPressed: _generateAndSharePdf,
            tooltip: "Share PDF",
          ),
        ],
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text("Cuisine: $cuisine",
                style:
                    const TextStyle(fontSize: 18, fontStyle: FontStyle.italic)),
            const SizedBox(height: 20),
            _buildUiSection("Starters", fullMenu['starters']),
            _buildUiSection("Main Course", fullMenu['main_course']),
            _buildUiSection("Breads & Rice",
                [...?fullMenu['breads'], ...?fullMenu['rice']]),
            _buildUiSection("Desserts", fullMenu['desserts']),
            _buildUiSection("Beverages", fullMenu['beverages']),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton.extended(
        backgroundColor: Colors.deepPurple,
        icon: const Icon(Icons.attach_money, color: Colors.white),
        label:
            const Text("Create Quote", style: TextStyle(color: Colors.white)),
        onPressed: () {
          // Since we are viewing history, we might not have the ID passed in directly.
          // For now, let's assume standard values or pass them if available.
          // Ideally, 'fullMenu' should contain the ID and Guest Count.

          Navigator.push(
            context,
            MaterialPageRoute(
              builder: (context) => PricingScreen(
                menuId: 0, // Placeholder if ID isn't available in this view yet
                guestCount: 500, // You can pass dynamic values here
                baseBudgetPerPlate: 400,
              ),
            ),
          );
        },
      ),
    );
  }

  // Normal UI Helper (Same as before)
  Widget _buildUiSection(String title, List<dynamic>? items) {
    if (items == null || items.isEmpty) return const SizedBox.shrink();
    return Card(
      margin: const EdgeInsets.only(bottom: 10),
      child: ListTile(
        title: Text(title,
            style: const TextStyle(
                fontWeight: FontWeight.bold, color: Colors.deepPurple)),
        subtitle: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: items
              .map((item) => Padding(
                    padding: const EdgeInsets.symmetric(vertical: 4),
                    child: Row(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        const Icon(Icons.check_circle,
                            size: 16, color: Colors.green),
                        const SizedBox(width: 8),
                        Expanded(child: Text(item.toString())),
                      ],
                    ),
                  ))
              .toList(),
        ),
      ),
    );
  }
}
