import 'package:flutter/material.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'pricing_screen.dart';
import '../translations.dart';
import '../main.dart';

class MenuDetailScreen extends StatelessWidget {
  final Map<String, dynamic> fullMenu;
  final String eventType;
  final String cuisine;
  final int menuId;
  final int guestCount;
  final int budgetPerPlate;

  const MenuDetailScreen({
    super.key,
    required this.fullMenu,
    required this.eventType,
    required this.cuisine,
    required this.menuId,
    required this.guestCount,
    required this.budgetPerPlate,
  });

  // --- PDF GENERATION (Kept in English for Font Safety) ---
  Future<void> _generateAndSharePdf() async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.Page(
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Header(
                level: 0,
                child: pw.Text("$eventType Menu ($cuisine)",
                    style: pw.TextStyle(
                        fontSize: 24, fontWeight: pw.FontWeight.bold)),
              ),
              pw.SizedBox(height: 10),
              pw.Text("Guests: $guestCount | Budget: Rs. $budgetPerPlate/plate",
                  style: const pw.TextStyle(
                      fontSize: 14, color: PdfColors.grey700)),
              pw.SizedBox(height: 20),
              _buildPdfSection("Starters", fullMenu['starters']),
              _buildPdfSection("Main Course", fullMenu['main_course']),
              _buildPdfSection("Breads & Rice",
                  [...?fullMenu['breads'], ...?fullMenu['rice']]),
              _buildPdfSection("Desserts", fullMenu['desserts']),
              _buildPdfSection("Beverages", fullMenu['beverages']),
              pw.SizedBox(height: 20),
              pw.Text("Generated by AI Catering Planner",
                  style:
                      const pw.TextStyle(fontSize: 12, color: PdfColors.grey)),
            ],
          );
        },
      ),
    );

    await Printing.sharePdf(
        bytes: await pdf.save(), filename: 'catering_menu.pdf');
  }

  // Helper for PDF Layout
  pw.Widget _buildPdfSection(String title, List<dynamic>? items) {
    if (items == null || items.isEmpty) return pw.SizedBox.shrink();
    return pw.Container(
      margin: const pw.EdgeInsets.only(bottom: 10),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(title,
              style: pw.TextStyle(
                  fontSize: 16,
                  fontWeight: pw.FontWeight.bold,
                  color: PdfColors.blueGrey800)),
          ...items.map((item) => pw.Bullet(text: item.toString())),
          pw.SizedBox(height: 5),
        ],
      ),
    );
  }

  // --- UI BUILD ---
  @override
  Widget build(BuildContext context) {
    // Wrap UI in ValueListenableBuilder for real-time translation
    return ValueListenableBuilder<String>(
      valueListenable: currentLanguage,
      builder: (context, lang, child) {
        // Helper to get translation
        String t(String key) => AppTranslations.get(lang, key);

        return Scaffold(
          appBar: AppBar(
            title: Text("$eventType Menu"),
            backgroundColor: Colors.deepPurple,
            foregroundColor: Colors.white,
            actions: [
              IconButton(
                icon: const Icon(Icons.share),
                onPressed: _generateAndSharePdf,
                tooltip: t('share_pdf'), // Translated
              ),
            ],
          ),
          body: SingleChildScrollView(
            padding: const EdgeInsets.all(16.0),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                // INFO CARD
                Container(
                  width: double.infinity,
                  padding: const EdgeInsets.all(12),
                  color: Colors.deepPurple.shade50,
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text("${t('cuisine')}: $cuisine", // Translated "Cuisine"
                          style: const TextStyle(
                              fontSize: 16, fontWeight: FontWeight.bold)),
                      const SizedBox(height: 5),
                      Text(
                          "${t('guests')}: $guestCount  |  ${t('budget')}: ₹$budgetPerPlate"), // Translated
                    ],
                  ),
                ),
                const SizedBox(height: 20),

                _buildUiSection(t('starters'), fullMenu['starters']),
                _buildUiSection(t('main_course'), fullMenu['main_course']),
                _buildUiSection("${t('breads')} & ${t('rice')}",
                    [...?fullMenu['breads'], ...?fullMenu['rice']]),
                _buildUiSection(t('desserts'), fullMenu['desserts']),
                _buildUiSection(t('beverages'), fullMenu['beverages']),
              ],
            ),
          ),
          floatingActionButton: FloatingActionButton.extended(
            backgroundColor: Colors.deepPurple,
            icon: const Icon(Icons.attach_money, color: Colors.white),
            label: Text(t('create_quote'),
                style: const TextStyle(color: Colors.white)), // Translated
            onPressed: () {
              // 1. Calculate the TOTAL Base Cost here (Guests * Price)
              double totalBaseCost = (guestCount * budgetPerPlate).toDouble();

              // 2. Navigate to Pricing Screen
              Navigator.push(
                context,
                MaterialPageRoute(
                  builder: (context) => PricingScreen(
                    menuId: menuId,
                    guestCount: guestCount,
                    baseFoodCost: totalBaseCost,
                  ),
                ),
              );
            },
          ),
        );
      },
    );
  }

  Widget _buildUiSection(String title, List<dynamic>? items) {
    if (items == null || items.isEmpty) return const SizedBox.shrink();
    return Card(
      margin: const EdgeInsets.only(bottom: 10),
      child: ListTile(
        title: Text(title,
            style: const TextStyle(
                fontWeight: FontWeight.bold, color: Colors.deepPurple)),
        subtitle: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: items
              .map((item) => Padding(
                    padding: const EdgeInsets.symmetric(vertical: 4),
                    child: Row(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        const Icon(Icons.check_circle,
                            size: 16, color: Colors.green),
                        const SizedBox(width: 8),
                        Expanded(child: Text(item.toString())),
                      ],
                    ),
                  ))
              .toList(),
        ),
      ),
    );
  }
}
